In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
print(pd.__version__)

3.0.6

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
np.zeros(10)
np.ones(10)
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
a = np.array([1, 2, 3, 5, 7, 12])
a[2] = 10
a
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0,100,11)
#np.linspace(12,84,3)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
df.min()

model_year                        1975
origin                            Asia
fuel_type                       Diesel
drivetrain             All-wheel drive
num_doors                            2
engine_displacement               1590
num_cylinders                        4
horsepower                       171.0
vehicle_weight                    3320
acceleration                      14.0
fuel_efficiency_mpg               19.8
dtype: object

In [16]:
len(df)

10000

In [15]:
df['fuel_type'].nunique()

3

In [21]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [25]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [26]:
df['horsepower'].median()

np.float64(254.0)

In [42]:
df['horsepower'].fillna(252).median()

np.float64(252.0)

In [41]:
df['horsepower'].mode()[0]

np.float64(252.0)

In [65]:
asian_cars = df.loc[
    df['origin'] == 'Asia',
    ['vehicle_weight', 'model_year']
].head(7)

asian_cars

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [66]:
X = np.array(asian_cars)
XT = X.T
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [69]:
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [72]:
XTX = XT.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [73]:
np.linalg.matrix_rank(XTX)

np.int64(2)

In [74]:
XTXi = np.linalg.inv(XTX)

In [83]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [84]:
pre_w = X.dot(XTXi)
w = y.dot(pre_w)

In [85]:
w.sum()

np.float64(0.369196969049255)